TRAMP_O = \
	tramp/libc___libc_va_arg.o \
	tramp/libc__ctty.o \
	tramp/libc__dmesg.o \
	tramp/libc__exec.o \
	tramp/libc__exit.o \
	tramp/libc__iopl.o \
	tramp/libc__killf.o \
	tramp/libc__killu.o \
	tramp/libc__mfree.o \
	tramp/libc__newregion.o \
	tramp/libc__setcompat.o \
	tramp/libc__sysmesg.o \
	tramp/libc__uptime.o \
	tramp/libc_abort.o \
	tramp/libc_access.o \
	tramp/libc_alarm.o \
	tramp/libc_asctime.o \
	tramp/libc_atoi.o \
	tramp/libc_atol.o \
	tramp/libc_brk.o \
	tramp/libc_calloc.o \
	tramp/libc_cfgetispeed.o \
	tramp/libc_cfgetospeed.o \
	tramp/libc_cfsetispeed.o \
	tramp/libc_cfsetospeed.o \
	tramp/libc_chdir.o \
	tramp/libc_chmod.o \
	tramp/libc_chown.o \
	tramp/libc_chroot.o \
	tramp/libc_clearerr.o \
	tramp/libc_close.o \
	tramp/libc_closedir.o \
	tramp/libc_creat.o \
	tramp/libc_ctime.o \
	tramp/libc_dup.o \
	tramp/libc_dup2.o \
	tramp/libc_endgrent.o \
	tramp/libc_endpwent.o \
	tramp/libc_execl.o \
	tramp/libc_execle.o \
	tramp/libc_execlp.o \
	tramp/libc_execv.o \
	tramp/libc_execve.o \
	tramp/libc_execvp.o \
	tramp/libc_exit.o \
	tramp/libc_fchmod.o \
	tramp/libc_fchown.o \
	tramp/libc_fclose.o \
	tramp/libc_fcntl.o \
	tramp/libc_fdopen.o \
	tramp/libc_feof.o \
	tramp/libc_ferror.o \
	tramp/libc_fflush.o \
	tramp/libc_fgetc.o \
	tramp/libc_fgetgrent.o \
	tramp/libc_fgetpwent.o \
	tramp/libc_fgets.o \
	tramp/libc_fileno.o \
	tramp/libc_fileno.o \
	tramp/libc_fopen.o \
	tramp/libc_fork.o \
	tramp/libc_fprintf.o \
	tramp/libc_fputc.o \
	tramp/libc_fputs.o \
	tramp/libc_free.o \
	tramp/libc_fseek.o \
	tramp/libc_fstat.o \
	tramp/libc_ftell.o \
	tramp/libc_getcwd.o \
	tramp/libc_getegid.o \
	tramp/libc_getenv.o \
	tramp/libc_geteuid.o \
	tramp/libc_getgid.o \
	tramp/libc_getgrent.o \
	tramp/libc_getgrgid.o \
	tramp/libc_getgrnam.o \
	tramp/libc_getpassn.o \
	tramp/libc_getpgrp.o \
	tramp/libc_getpid.o \
	tramp/libc_getppid.o \
	tramp/libc_getpwent.o \
	tramp/libc_getpwnam.o \
	tramp/libc_getpwuid.o \
	tramp/libc_gets.o \
	tramp/libc_getuid.o \
	tramp/libc_gmtime.o \
	tramp/libc_inb.o \
	tramp/libc_inl.o \
	tramp/libc_insb.o \
	tramp/libc_insl.o \
	tramp/libc_insw.o \
	tramp/libc_inw.o \
	tramp/libc_ioctl.o \
	tramp/libc_isalnum.o \
	tramp/libc_isalpha.o \
	tramp/libc_isatty.o \
	tramp/libc_iscntrl.o \
	tramp/libc_isdigit.o \
	tramp/libc_islower.o \
	tramp/libc_isprint.o \
	tramp/libc_ispunct.o \
	tramp/libc_isspace.o \
	tramp/libc_isupper.o \
	tramp/libc_isxdigit.o \
	tramp/libc_kill.o \
	tramp/libc_link.o \
	tramp/libc_localtime.o \
	tramp/libc_longjmp.o \
	tramp/libc_lseek.o \
	tramp/libc_malloc.o \
	tramp/libc_md5.o \
	tramp/libc_md5a.o \
	tramp/libc_memccpy.o \
	tramp/libc_memchr.o \
	tramp/libc_memcmp.o \
	tramp/libc_memcpy.o \
	tramp/libc_memcpy.o \
	tramp/libc_memmove.o \
	tramp/libc_memset.o \
	tramp/libc_memset.o \
	tramp/libc_mkdir.o \
	tramp/libc_mkfifo.o \
	tramp/libc_mknod.o \
	tramp/libc_mktime.o \
	tramp/libc_mount.o \
	tramp/libc_open.o \
	tramp/libc_opendir.o \
	tramp/libc_outb.o \
	tramp/libc_outl.o \
	tramp/libc_outsb.o \
	tramp/libc_outsl.o \
	tramp/libc_outsw.o \
	tramp/libc_outw.o \
	tramp/libc_pause.o \
	tramp/libc_perror.o \
	tramp/libc_pipe.o \
	tramp/libc_printf.o \
	tramp/libc_putpwent.o \
	tramp/libc_puts.o \
	tramp/libc_qsort.o \
	tramp/libc_raise.o \
	tramp/libc_read.o \
	tramp/libc_readdir.o \
	tramp/libc_realloc.o \
	tramp/libc_reboot.o \
	tramp/libc_remove.o \
	tramp/libc_rename.o \
	tramp/libc_rewind.o \
	tramp/libc_rewinddir.o \
	tramp/libc_rmdir.o \
	tramp/libc_sbrk.o \
	tramp/libc_seekdir.o \
	tramp/libc_setbuf.o \
	tramp/libc_setbuffer.o \
	tramp/libc_setgid.o \
	tramp/libc_setgrent.o \
	tramp/libc_setjmp.o \
	tramp/libc_setlinebuf.o \
	tramp/libc_setpwent.o \
	tramp/libc_setsid.o \
	tramp/libc_setuid.o \
	tramp/libc_setvbuf.o \
	tramp/libc_signal.o \
	tramp/libc_sleep.o \
	tramp/libc_snprintf.o \
	tramp/libc_sprintf.o \
	tramp/libc_stat.o \
	tramp/libc_statfs.o \
	tramp/libc_stime.o \
	tramp/libc_strcat.o \
	tramp/libc_strchr.o \
	tramp/libc_strcmp.o \
	tramp/libc_strcpy.o \
	tramp/libc_strcspn.o \
	tramp/libc_strdup.o \
	tramp/libc_strerror.o \
	tramp/libc_strlen.o \
	tramp/libc_strncat.o \
	tramp/libc_strncmp.o \
	tramp/libc_strncpy.o \
	tramp/libc_strpbrk.o \
	tramp/libc_strrchr.o \
	tramp/libc_strspn.o \
	tramp/libc_strtok.o \
	tramp/libc_sync.o \
	tramp/libc_system.o \
	tramp/libc_tcgetattr.o \
	tramp/libc_tcsetattr.o \
	tramp/libc_telldir.o \
	tramp/libc_time.o \
	tramp/libc_timegm.o \
	tramp/libc_times.o \
	tramp/libc_ttyname.o \
	tramp/libc_ttyname3.o \
	tramp/libc_tzset.o \
	tramp/libc_ulimit.o \
	tramp/libc_umask.o \
	tramp/libc_umount.o \
	tramp/libc_uname.o \
	tramp/libc_ungetc.o \
	tramp/libc_unlink.o \
	tramp/libc_utime.o \
	tramp/libc_vfprintf.o \
	tramp/libc_vprintf.o \
	tramp/libc_vsnprintf.o \
	tramp/libc_vsprintf.o \
	tramp/libc_wait.o \
	tramp/libc_waitpid.o \
	tramp/libc_write.o \
	tramp/libc_strsignal.o \
	tramp/libc_ftime.o \
	tramp/libc__ftime.o \
	tramp/libc__sfilsys.o \
	tramp/libc__readwrite.o \

