#!/bin/sh
#
# Copyright (c) Piotr Durlej
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#

set -e

rm -Rf tree
cp -Rf ../tree tree

mkdir -p tree/bin		\
	 tree/dev		\
	 tree/tmp		\
	 tree/udd		\
	 tree/mnt		\
	 tree/usr/guest		\
	 tree/usr/mdec		\
	 tree/usr/spool/mail	\
	 tree/usr/dbg		\
	 tree/usr/compat	\
	 tree/usr/tmp

cp -f ../cmd/sh/sh	tree/bin/sh
cp -f ../cmd/vi/vi	tree/bin/vix
cp -f ../cmd/shlib/shlib tree/bin/shlib
cp -f ../cmd/shlib/shello tree/usr/dbg/shello

cp -f ../kern/kern	tree/usr/mdec/xenus
cp -f ../boot/boot.bin	tree/usr/mdec/boot
cp -f ../boot/pcmbr.bin	tree/usr/mdec/pcmbr

for x in ../cmd/bin/*; do
	test -x $x && cp -f $x tree/bin/$(basename $x)
done

for x in ../cmd/sbin/* ; do
	test -x $x && cp -f $x tree/bin/$(basename $x)
done

for x in ../cmd/dbg/*; do
	test -x $x && cp -f $x tree/usr/dbg/$(basename $x)
done

cp ../cmd/comp7/v7unx tree/usr/compat/v7unx
cp ../cmd/comp/minix tree/usr/compat/minix

tar cf base.tar -C tree .
