SYS_O = \
	xenus/sys__sysmesg.o \
	xenus/sys__exit.o \
	xenus/sys_brk.o \
	xenus/sys_getpid.o \
	xenus/sys_getppid.o \
	xenus/sys_getuid.o \
	xenus/sys_geteuid.o \
	xenus/sys_getgid.o \
	xenus/sys_getegid.o \
	xenus/sys_signal.o \
	xenus/sys_kill.o \
	xenus/sys_mknod.o \
	xenus/sys_open.o \
	xenus/sys_close.o \
	xenus/sys_read.o \
	xenus/sys_write.o \
	xenus/sys_lseek.o \
	xenus/sys_fstat.o \
	xenus/sys_fchmod.o \
	xenus/sys_fchown.o \
	xenus/sys_access.o \
	xenus/sys_chdir.o \
	xenus/sys_chroot.o \
	xenus/sys_unlink.o \
	xenus/sys_mkdir.o \
	xenus/sys_rmdir.o \
	xenus/sys_link.o \
	xenus/sys_rename.o \
	xenus/sys_ioctl.o \
	xenus/sys_fcntl.o \
	xenus/sys__exec.o \
	xenus/sys_fork.o \
	xenus/sys_wait.o \
	xenus/sys_pause.o \
	xenus/sys_time.o \
	xenus/sys_stime.o \
	xenus/sys_alarm.o \
	xenus/sys_setuid.o \
	xenus/sys_setgid.o \
	xenus/sys_setsid.o \
	xenus/sys_ttyname3.o \
	xenus/sys_statfs.o \
	xenus/sys_mount.o \
	xenus/sys_umount.o \
	xenus/sys_sync.o \
	xenus/sys_umask.o \
	xenus/sys__ctty.o \
	xenus/sys_pipe.o \
	xenus/sys__killf.o \
	xenus/sys_uname.o \
	xenus/sys__iopl.o \
	xenus/sys__mfree.o \
	xenus/sys_reboot.o \
	xenus/sys_stat.o \
	xenus/sys_chmod.o \
	xenus/sys_chown.o \
	xenus/sys_dup.o \
	xenus/sys_dup2.o \
	xenus/sys__uptime.o \
	xenus/sys_sbrk.o \
	xenus/sys__dmesg.o \
	xenus/sys_sleep.o \
	xenus/sys__killu.o \
	xenus/sys_utime.o \
	xenus/sys__newregion.o \
	xenus/sys__setcompat.o \
	xenus/sys_waitpid.o \
	xenus/sys_times.o \

